artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.8.5
    provides:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.6.2
  "@daiyam/artifact-vsx-ts":
    version: 0.8.1
  "@daiyam/artifact-vsx-zokugun":
    version: 0.3.1
  "@daiyam/artifact-vsx-bundle-ncc":
    version: 0.4.0
