$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.9.0/schemas/v2/install.json
artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.12.0
    requires:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.9.0
  "@daiyam/artifact-vsx-ts":
    version: 0.11.8
  "@daiyam/artifact-vsx-zokugun":
    version: 0.4.2
  "@daiyam/artifact-vsx-bundle-ncc":
    version: 0.4.1
  "@daiyam/artifact-gh-issuehub":
    version: 0.6.3
variables:
  DISCUSSION_ID: 49
  ISSUE_ID: 48
