name: "CI - Pull Request: Build & Lint"

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install zizmor
        run: |
          pipx install zizmor

      - name: Setup Node.js environment
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      # - name: Test
      #   run: |
      #     npm run test

      - name: Lint code
        run: |
          npm run lint:all

      - name: Lint commit
        run: |
          npx commitlint --from "${BASE_SHA}" --to "${HEAD_SHA}" --verbose
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
